/* Samdo FC supporters — the thank-you wall.
   Each line: ['Name', 'Place', amount in NPR]. Totals and charts are worked out automatically.
   PHOTO (optional): add the photo's file name as a 4th item, e.g. ["Gabba", "France", 17500, "gabba.jpg"],
   and put a small square photo in images/web/supporters/ (Claude can prepare it from 'Supporter photos').
   No photo = the card shows the person's initials.
   To add a new season, copy a block and change the year. */
window.SAMDO_SUPPORTERS = [
  { season: '2026', note: 'The support behind our fifth title', gifts: [
    ["Mingchung", "USA", 10000, "mingchung.jpg"],
    ["Gabba", "France", 17500, "gabba.jpg"],
    ["Dolkar", "Samdo", 5050, "dolkar.jpg"],
    ["Tsering Phuntsok", "Samdo", 5000],
    ["Ngodup", "Samdo", 7000],
    ["Nuru Sherpa", "Sherpa", 5000, "nuru-sherpa.jpg"],
    ["Norling Hotel", "Sama Gaun", 10000, "norling-hotel.jpg"],
    ["Yak Hotel", "Samdo", 7500, "yak-hotel.jpg"],
    ["Pasang Choephel", "France", 15000, "pasang-choephel.jpg"],
    ["Pasang Bhuti", "Samdo", 1500, "pasang-bhuti.jpg"],
    ["Tashi Lhamo", "Samdo", 1500, "tashi-lhamo.jpg"],
    ["Maila Dai", "Samdo", 5000, "maila-dai.jpg"],
    ["Dawa Dolma", "Samdo", 2000, "dawa-dolma.jpg"],
    ["Lopon Dawa Dhondup", "Samdo", 10000, "lopon-dawa-dhondup.jpg"],
    ["Shala School Party Donation", "Shala", 8100, "shala-school-party-donation.jpg"],
    ["Dawa Wangyal", "Sama Gaun", 1500],
    ["Lama Jigme", "Sama Gaun", 7500],
    ["Lambu and Sons", "Samdo", 3050, "lambu-and-sons.jpg"],
    ["Rinzin Dorje", "France", 50000, "rinzin-dorje.jpg"],
    ["Tenzin (Echea)", "India", 17500, "tenzin-echea.jpg"],
    ["Dawa Sir", "France", 8800, "dawa-sir.jpg"],
    ["Karang Grg", "Samdo", 1500],
    ["Gyang Lama", "Samdo", 500],
    ["Unknown", "Samdo", 1000],
    ["Nyima Choedon", "Samdo", 3500],
    ["Yangzom", "USA", 25000, "yangzom.jpg"],
    ["Mae Dorjee", "Samdo", 11500, "mae-dorjee.jpg"],
    ["Dawa Gyaltsen", "France", 17500, "dawa-gyaltsen.jpg"],
  ] },
  { season: '2025', note: 'The support that carried us through 2025', gifts: [
    ["Khenpo Mingmar", "Samdo", 10000, "khenpo-mingmar.jpg"],
    ["Penpa Gyalpo", "Samdo", 15000, "penpa-gyalpo.jpg"],
    ["Ramesh", "Tilchi", 5000, "ramesh.jpg"],
    ["Miss Youdon", "Bhimtang", 5000, "miss-youdon.jpg"],
    ["Khenpo Nyima", "Samdo", 5000, "khenpo-nyima.jpg"],
    ["Tulku Mingmar", "Samdo", 25000, "tulku-mingmar.jpg"],
    ["Tashi Tsering", "Samdo", 19500],
    ["Peace Hotel", "Samdo", 15000, "peace-hotel.jpg"],
    ["Tsering Dhargyal", "Samdo", 5000, "tsering-dhargyal.jpg"],
    ["Khenpo Jinpa", "Samdo", 12000],
    ["Gabba", "France", 5000, "gabba.jpg"],
    ["Dolkar", "Samdo", 5250, "dolkar.jpg"],
    ["Lhakpa Tsering", "Samdo", 5000, "lhakpa-tsering.jpg"],
    ["Nyo", "Samdo", 1500],
    ["Pasang", "Samdo", 4250],
    ["Lhakpa Choezom", "Samdo", 2100, "lhakpa-choezom.jpg"],
    ["Pema Lhamo", "Samdo", 2500, "pema-lhamo.jpg"],
    ["Lema", "Samdo", 1000],
    ["AMA Samuha", "Samdo", 5500],
    ["Yak Hotel", "Samdo", 6000, "yak-hotel.jpg"],
    ["Tashi Deckyi", "Samdo", 5500],
    ["Tsering Youdon", "France", 5000, "tsering-youdon.jpg"],
    ["Pasang Tsering", "Samdo", 5000, "pasang-tsering.jpg"],
    ["Pema Dekyi Lama", "USA", 10000, "pema-dekyi-lama.jpg"],
    ["Sangeeta", "Tilchi", 3000],
  ] },
];
/* Places outside Nepal (used for the 'countries' count). */
window.SAMDO_ABROAD = ['France', 'USA', 'India'];
